#!/bin/bash

# File: fuz
# Author: Abhishek Yadav
# Upstream: https://github.com/b4skyx/unix-scripts

# Fzf script to preview files using bat and edit them in vim
# I use bat because of the pretty syntax highlighting

set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    "$EDITOR" "$file_to_edit"
    main "$file_to_edit"
  fi
}

select_file() {
  given_file="$1"
  fzf --preview="bat --style=numbers --color=always --line-range :500 {}" --preview-window=right:70%:wrap --query="$given_file"
}

main
