#!/bin/bash

# File: live_reload
# Author: Abhishek Yadav
# Upstream: https://github.com/b4skyx/unix-scripts

# Update the terminal colors on the fly by directly writing the ASCII sequences to the pts.
# Works in almost all terminals
# Reads the colors from your xresources

# Documentation about the ASCII sequences available in the urxvt source.
# https://github.com/exg/rxvt-unicode/blob/cbadfa977cd8d80c13501e686dd0b3840903d1dc/doc/rxvt.7.man.in#L2324-L2354


# Function to get the desired color form xrdb

xrdb_query() {
    value=$(xrdb -query | grep -i "^*\.$1:" | cut -f 2)
    if [ -n "${value}" ]; then
      echo "${value}"
      return 0
    fi
  return 1
}

sequences=""
for i in $(seq 0 15); do
  sequences+="\033]4;${i};$(xrdb_query "color${i}")\007"
done

# foreground, background, and cursor.
sequences+="\\033]10;$(xrdb_query foreground)\\007"
sequences+="\\033]11;$(xrdb_query background)\\007"
sequences+="\\033]12;$(xrdb_query cursorColor)\\007"


# Write colors to the terminals
for term in /dev/pts/[0-9]*; do
  printf "%b" "${sequences}" > "${term}" &
done
echo "All terminal colors reloaded"
