#!/bin/bash

# File: newmail
# Author: Abhishek Yadav
# Upstream: https://github.com/b4skyx/unix-scripts

# Script to sync mail with neomutt and notify the updates.
# I use it with my mail module in polybar

unread="$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/* 2>/dev/null -type f | wc -l 2>/dev/null)"

icon=""
pidof mbsync >/dev/null 2>&1 && icon=" "

[ "$unread" = "0" ] && [ "$unread" = "" ] || echo " $unread$icon"

if [ -e /tmp/unread-mail-count ]
then
	mailread=$(cat /tmp/unread-mail-count)
	if [[ "$unread" -gt "$b$mailread" ]] && [ "" != "$icon" ]
	then
		echo "$unread" > /tmp/unread-mail-count
	fi
else
	echo "$unread" > /tmp/unread-mail-count
fi
